#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Install SDDM"
echo

sudo pacman -S --noconfirm sddm

echo
echo "Done!"
echo

echo
echo "Set Graphical Target"
echo

sudo systemctl set-default graphical.target

echo
echo "Done!"
echo

echo
echo "Enable SDDM"
echo

sudo systemctl enable sddm

echo
echo "Done!"
echo

echo
echo "Install Niri and Deps"
echo

PKGS=(
	'niri'
	'gnome-keyring'
	'xwayland-satellite'
	'xdg-desktop-portal-gtk'
	'xdg-desktop-portal-gnome'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Noctalia"
echo

sudo pacman -S --noconfirm noctalia

echo
echo "Done!"
echo

echo
echo "Install Noctalia Core Deps"
echo

PKGS=(
	'ddcutil'
	'cliphist'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Theme"
echo

PKGS=(
	'adw-gtk-theme'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#
