#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Install Cosmic DE"
echo

PKGS=(
	'cosmic'
	'gnome-keyring'
	'xdg-desktop-portal-gtk'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Set Graphical Target"
echo

sudo systemctl set-default graphical.target

echo
echo "Done!"
echo

echo
echo "Enable Cosmic Greeter"
echo

sudo systemctl enable cosmic-greeter.service

echo
echo "Done!"
echo

echo
echo "Install Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
	'fastfetch'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#

#--------------------------------------#
# System Utils:                        #
# - Lact                               #
# - Flat Seal                          #
# - Warehouse                          #
#                                      #
# Extra Apps                           #
# - VLC                                #
# - Loupe                              #
# - Calendar                           #
#                                      #
# Gaming Utils:                        #
# - Lutris                             #
# - Goverlay                           #
# - Proton Plus                        #
# - Proton Tricks                      #
#--------------------------------------#
