#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Install Gnome Apps"
echo

PKGS=(
	'vlc'
	'loupe'
	'papers'
	'gnome-text-editor'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Set Default Apps"
echo

curl -Lo $HOME/.config/mimeapps.list https://raw.githubusercontent.com/kitkat6464/EnterTheVoid/refs/heads/niri/.config/mimeapps.list

echo
echo "Done!"
echo

echo
echo "Install Extra Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
	'fastfetch'
	'vlc-plugins-all'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#
