#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Install Game Stuff"
echo

PKGS=(
	'steam'
	'mangohud'
	'gamescope'
	'umu-launcher'
	'lib32-mangohud'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install ScopeBuddy and wlr-randr"
echo

sudo pacman -S wlr-randr --noconfirm
sudo wget -O /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.4.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#

#--------------------------------------#
# System Utils:                        #
# - Lact                               #
# - Flat Seal                          #
# - Warehouse                          #
#                                      #
# Extra Apps                           #
# - VLC                                #
# - Loupe                              #
# - Calendar                           #
#                                      #
# Gaming Utils:                        #
# - Lutris                             #
# - Goverlay                           #
# - Proton Plus                        #
# - Proton Tricks                      #
#--------------------------------------#
