#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Install Cosmic DE"
echo

PKGS=(
	'cosmic'
	'gnome-keyring'
	'xdg-desktop-portal-gtk'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Set Graphical Target"
echo

sudo systemctl set-default graphical.target

echo
echo "Done!"
echo

echo
echo "Enable Cosmic Greeter"
echo

sudo systemctl enable cosmic-greeter.service

echo
echo "Done!"
echo

echo
echo "Install Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
	'fastfetch'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Game Stuff"
echo

PKGS=(
	'steam'
	'mangohud'
	'gamescope'
	'umu-launcher'
	'lib32-mangohud'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install ScopeBuddy and wlr-randr"
echo

sudo pacman -S wlr-randr --noconfirm
sudo wget -O /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.4.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

echo
echo "Install System Tools"
echo

PKGS=(
	'scx-tools'
	'scx-scheds'
	'zram-generator'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Apply Optimsations"
echo

sudo wget -O /etc/sysctl.d/70-aleph-settings.conf https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/70-aleph-settings.conf

sudo wget -O /etc/sysctl.d/99-splitlock.conf https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/99-splitlock.conf

sudo sysctl --system

sudo wget -O /etc/systemd/zram-generator.conf https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/zram-generator.conf

sudo wget -O /etc/udev/rules.d/30-zram.rules https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/30-zram.rules

sudo systemctl daemon-reload

sudo systemctl start /dev/zram0

sudo systemctl enable --now scx_loader.service

sudo wget -O /etc/scx_loader.toml https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/scx_loader.toml

sudo systemctl restart scx_loader.service

sudo wget -O /usr/lib/modules-load.d/ntsync.conf https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/ntsync.conf

sudo wget -O /etc/security/limits.conf https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/midgard/sys_cfgs/limits.conf

echo
echo "Done!"
echo

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#

#--------------------------------------#
# System Utils:                        #
# - Lact                               #
# - Flat Seal                          #
# - Warehouse                          #
#                                      #
# Extra Apps                           #
# - VLC                                #
# - Loupe                              #
# - Calendar                           #
#                                      #
# Gaming Utils:                        #
# - Lutris                             #
# - Goverlay                           #
# - Proton Plus                        #
# - Proton Tricks                      #
#--------------------------------------#
