#!/usr/bin/env bash

#----------------------------------------#
# Start - Catrina's Post Setup - Midgard #
#----------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu

echo
echo "Done!"
echo

echo
echo "Install Portal and Keyring"
echo

PKGS=(
	'xdg-desktop-portal-gtk'
	'gnome-keyring'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
	'fastfetch'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Game Stuff"
echo

PKGS=(
	'steam'
	'mangohud'
	'gamescope'
	'umu-launcher'
	'lib32-mangohud'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install ScopeBuddy and wlr-randr"
echo

sudo pacman -S wlr-randr --noconfirm
sudo wget -O /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.4.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

echo
echo "Install System Tools"
echo

PKGS=(
	'scx-tools'
	'scx-scheds'
	'zram-generator'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#--------------------------------------#
# End - Catrina's Post Setup - Midgard #
#--------------------------------------#

#--------------------------------------#
# System Utils:                        #
# - Flat Seal                          #
# - Warehouse                          #
# - Lact                               #
#                                      #
# Gaming Utils:                        #
# - Lutris                             #
# - Goverlay                           #
# - Proton Plus                        #
# - Proton Tricks                      #
#--------------------------------------#
