#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's Additional Setup After Installing Using DMS Installer
#-------------------------------------------------------------------------

echo
echo "Refreshing Repo Information"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing Core Components From The Main Repo"
echo

PKGS=(
        'xdg-desktop-portal-gnome'
        'gnome-keyring'
        'wlr-randr'
        'cava'
        'flatpak'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Theming Packages From The Main Repo"
echo

pacman -S --noconfirm \
  adw-gtk-theme \
  nwg-look

PKGS=(
        'adw-gtk-theme'
        'nwg-look'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing Core Applications From The Main Repo"
echo

PKGS=(
        'nautilus'
        'loupe'
        'decibels'
        'showtime'
        'papers'
        'gnome-text-editor'
        'lact'
        'gpu-screen-recorder-gtk'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing Packages From The AUR. Skull Emoji"
echo

paru -S --noconfirm qt6ct-kde
paru -S --noconfirm bazaar

echo
echo "Done!"
echo
