#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's Additional Setup After Installing Using DMS Installer
#-------------------------------------------------------------------------

echo
echo "Refreshing Repo Information"
echo

pikman upgrade

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing Core Components From The Main Repo"
echo

pikman install wlr-randr

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing Core Applications From The Main Repo"
echo

pikman install loupe gnome-music papers gnome-text-editor firefox lact bazaar

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Setting Up Default Apps"
echo

cd $HOME/.config
wget https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/pikadms/.config/mimeapps.list

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Installing ScopeBuddy For GameScope"
echo

sudo curl -Lo /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.4.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

#-------------------------------------------------------------------------
