#!/usr/bin/env bash

#---------------------------------------------------#
# Start - Catrina's Post Setup - Noctalia Installer #
#---------------------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu

echo
echo "Done!"
echo

echo
echo "Install SDDM"
echo

PKGS=(
	'sddm'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Niri and Deps"
echo

PKGS=(
	'niri'
	'gnome-keyring'
	'xwayland-satellite'
	'xdg-desktop-portal-gtk'
	'xdg-desktop-portal-gnome'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Noctalia Shell"
echo

yay -S --noconfirm noctalia-shell

echo
echo "Done!"
echo

echo
echo "Install Noctalia Core Deps"
echo

PKGS=(
	'cava'
	'ddcutil'
	'cliphist'
	'wlsunset'
	'wlr-randr'
	'wl-clipboard'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Noctalia Plugin Deps"
echo

PKGS=(
	'evtest'
	'gpu-screen-recorder'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Theming Apps"
echo

PKGS=(
	'qt6ct'
	'nwg-look'
	'adw-gtk-theme'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Cursor and Icon Themes"
echo

yay -S --noconfirm rose-pine-cursor papirus-icon-theme-git

echo
echo "Done!"
echo

echo
echo "Install Gnome Apps"
echo

PKGS=(
	'loupe'
	'papers'
	'secrets'
	'gnome-text-editor'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Additional Apps"
echo

PKGS=(
	'vlc'
	'lact'
	'kitty'
	'bazaar'
	'protonplus'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Setting Default Apps"
echo

sudo curl -Lo $HOME/.config/mimeapps.list https://raw.githubusercontent.com/kitkat6464/my_configs/refs/heads/configs/.config/mimeapps.list

echo
echo "Done!"
echo

echo
echo "Install SCX Tools"
echo

PKGS=(
	'scx-tools'
	'scx-scheds'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Enable Services"
echo

sudo systemctl enable sddm

echo
echo "Done!"
echo

#-------------------------------------------------#
# End - Catrina's Post Setup - Noctalia Installer #
#-------------------------------------------------#
